apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: java-app
  labels:
    app: {{ .Values.app.label }}
spec:
  selector:
    app: {{ .Values.app.label }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}
