# Application configuration
app:
  name: java-app
  label: java-app

# Image configuration
image:
  repository: arvind005/java-app
  tag: jv81
  pullSecretName: my-dockerhub-secret

# Deployment configuration
deployment:
  replicas: 4
  containerPort: 9098

# Service configuration
service:
  name: java-svc
  port: 80
  targetPort: 9098
  type: ClusterIP

# Ingress configuration
ingress:
  name: java-ing
  host: www.flowci.in
  tlsSecretName: flowci-tls
