# Application configuration
app:
  name: java-app
  label: java-app

# Image configuration
image:
  repository: arvind005/java-app
  tag: jv80

# Deployment configuration
deployment:
  replicas: 4
  containerPort: 9098

# Service configuration
service:
  name: java-svc
  port: 80
  targetPort: 9098
  type: NodePort

# Ingress configuration
ingress:
  name: java-ing
  host: flowci.in
  tlsSecretName: flowci-tls
